# -*- coding: utf-8 -*-
"""AIUTS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e_j2iIrhKtXuc_iTpjDBPOxUIQ8bZxby
"""

!pip install experta

!pip install --upgrade frozendict

from experta import *

class PlantPestDiagnosis(KnowledgeEngine):
    @Rule(Fact(leaf_yellowing=True) & Fact(black_spots=True))
    def fungi(self):
        print("Diagnosis: Tanaman terkena Jamur.")

    @Rule(Fact(leaf_yellowing=True) & Fact(black_spots=False))
    def aphids(self):
        print("Diagnosis: Tanaman terkena Kutu Daun.")

    @Rule(Fact(leaf_holes=True))
    def caterpillars(self):
        print("Diagnosis: Tanaman terkena Ulat.")

    @Rule(Fact(plant_wilting=True) & Fact(leaf_yellowing=True))
    def root_nematodes(self):
        print("Diagnosis: Tanaman terkena Nematoda Akar.")

    @Rule(Fact(leaf_yellowing=False) & Fact(black_spots=False) & Fact(leaf_holes=False) & Fact(plant_wilting=False))
    def healthy(self):
        print("Diagnosis: Tanaman tampaknya sehat.")

def get_input():
    def ask(question):
        return input(question + " (yes/no): ").strip().lower() == "yes"

    return {
        "leaf_yellowing": ask("Apakah daun menguning?"),
        "black_spots": ask("Apakah terdapat bercak hitam pada daun?"),
        "leaf_holes": ask("Apakah daun berlubang?"),
        "plant_wilting": ask("Apakah tanaman tampak layu?")
    }

if __name__ == "__main__":
    symptoms = get_input()
    engine = PlantPestDiagnosis()
    engine.reset()

    for symptom, present in symptoms.items():
        engine.declare(Fact(**{symptom: present}))

    engine.run()